### ISSUE TITLE
com.wyait.common.utils这个包下的DateUtil,ValidateUtil找不到

### ISSUE THREAD

**Issue by grainrain** [wyait/manage#1]

**Comment by ligeng33200** [comment]
对的 我也遇到了这个问题

**Comment by wyait** [comment]
解决方案1：wyait-common项目下载到本地后，install到maven仓库中；
解决方案2：直接将wyait-common里面的工具类拷贝到wyait-manager项目中，删除wyait-common依赖也可以；

**Comment by wyait** [comment]
解决方案3：自行实现DateUtil、ValidateUtil工具类

**Comment by InSkyCat** [comment]
大神，你那里 没有出现这种问题吗？ 能否给解释解释，出这种问题的原因呐，也方便以后遇到类似问题好有个解决思路，还有我的项目里出现:spring-boot-starter-web  ,commons-lang3，commons-io  这仨 omitted for duplicate   ，这个有没有问题呐 
 <dependency>
            <groupId>com.wyait.common</groupId>
            <artifactId>wyait-common</artifactId>
            <version>1.0-SNAPSHOT</version>
<exclusions>
                    <exclusion>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-starter-web</artifactId>
                    </exclusion>
                <exclusion>
                    <groupId>org.apache.commons</groupId>
                    <artifactId>commons-lang3</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>commons-io</groupId>
                    <artifactId>commons-io</artifactId>
                </exclusion>

            </exclusions>

**Comment by InSkyCat** [comment]
大神，你那里 没有出现这种问题吗？ 能否给解释解释，出这种问题的原因呐，也方便以后遇到类似问题好有个解决思路，还有我的项目里出现:spring-boot-starter-web ,commons-lang3，commons-io 这仨 omitted for duplicate ，这个有没有问题呐
`<dependency>
            <groupId>com.wyait.common</groupId>
            <artifactId>wyait-common</artifactId>
            <version>1.0-SNAPSHOT</version>
            <exclusions>
                    <exclusion>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-starter-web</artifactId>
                    </exclusion>
                <exclusion>
                    <groupId>org.apache.commons</groupId>
                    <artifactId>commons-lang3</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>commons-io</groupId>
                    <artifactId>commons-io</artifactId>
                </exclusion>

            </exclusions>
        </dependency>`
