### ISSUE TITLE
打成war包部署到tomcat后的访问路径是什么？

### ISSUE THREAD

**Issue by antpress** [wyait/manage#3]
试了好多都不可以访问，/wyait-manage不行/wyait-manage-1.2.0也不行，对IDEA不是很熟悉，求教原因，不胜感激！

Update：问题已经解决

but还有一个问题  就是不是很明白  你在配置数据库的时候有两个properties,一个是application-dev和application-prod；  请问具体用的是哪一个  还有就是多数据源的配置是否可以忽略？

**Comment by wyait** [comment]
参考博客：http://blog.51cto.com/wyait/2082803 spring boot + mybatis + layui + shiro后台权限管理系统
里面有详细的说明，application-dev和application-prod只是区分开发和线上环境配置。

**Comment by wyait** [comment]
多数据源的配置，可以改为单数据源配置，下个版本会区分说明。当前也可参考博客：http://blog.51cto.com/wyait/1969626

**Comment by ShayneLee8** [comment]
> 试了好多都不可以访问，/wyait-manage不行/wyait-manage-1.2.0也不行，对IDEA不是很熟悉，求教原因，不胜感激！
> 
> Update：问题已经解决
> 
我还是不知道怎么解决， 博文里面也没有提到 tomcat 部署时怎么配置和访问呀

**Comment by antpress** [comment]
> > 试了好多都不可以访问，/wyait-manage不行/wyait-manage-1.2.0也不行，对IDEA不是很熟悉，求教原因，不胜感激！
> > Update：问题已经解决
> 
> 我还是不知道怎么解决， 博文里面也没有提到 tomcat 部署时怎么配置和访问呀

我使用的是springboot直接打包成jar，然后运行jar包，直接访问IP+Port即可
